### ISSUE TITLE
When i run pip for install package ,there is a error message

### ISSUE THREAD

**Issue by hareteam** [honmaple/maple-blog#1]
Python version:3/6
pip: 9.0.1
When i Install necessary package by using 'pip install -r requestments.txt ' , there is a error message:
‘’‘
 Could not find a version that satisfies the requirement Flask-SQLAlchemy==3.0.dev20161113 (from -r ./requirements.txt (line 16)) (from versions: 0.5, 0.6, 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 1.0, 2.0, 2.1, 2.2)
No matching distribution found for Flask-SQLAlchemy==3.0.dev20161113 (from -r ./requirements.txt (line 16))
’‘’

**Comment by honmaple** [comment]
Now just use
```
pip install flask-sqlalchemy
```

**Comment by honmaple** [comment]
About **flask-maple**
```
git clone https://github.com/honmaple/flask-maple
cd flask-maple 
python setup.py install
```
About **org.py**
see [org-python](https://github.com/honmaple/org-python)

About **fortune**
see [fortune](https://github.com/honmaple/fortune)

**Comment by hareteam** [comment]
And i must remove 'Flask-SQLAlchemy==3.0.dev  ' this line ,right ?

**Comment by honmaple** [comment]
Yes. Or you can delete `Flask-SQLAlchemy==3.0.dev` and install it later

**Comment by hareteam** [comment]
Ok, thank u very much 。:)

**Comment by honmaple** [comment]
You are welcome.
