### ISSUE TITLE
Error: No such command "create_user".

### ISSUE THREAD

**Issue by banduoba** [honmaple/maple-blog#4]
如图错误,请问如何解决呢,刚刚接触 python 使用的 pipenv 虚拟环境安装的
<img width="1292" alt="xnip2019-01-13_10-04-34" src="https://user-images.githubusercontent.com/4811366/51080668-03fd5280-171b-11e9-9bab-56fe55f23552.png">

**Comment by honmaple** [comment]
新版flask使用的应该是`create-user`， 可以`python runserver.py --help`查看

**Comment by banduoba** [comment]
谢谢!
通过`python runserver.py --help` 已解决
不过后台登录进去是空白
<img width="1175" alt="wx20190114-162340 2x" src="https://user-images.githubusercontent.com/4811366/51102174-e1516380-1818-11e9-8bdb-483cef021346.png">

**Comment by honmaple** [comment]
后台需要`python runserver.py token -u <username>`得到token, 然后浏览器访问`http://127.0.0.1:8001/login?token=<token>`登陆

**Comment by banduoba** [comment]
> 后台需要`python runserver.py token -u <username>`得到token, 然后浏览器访问`http://127.0.0.1:8001/login?token=<token>`登陆

根据回答已解决,非常感谢,顺便问下可以认识交流下么

**Comment by honmaple** [comment]
有问题可以发邮件或issue的，很乐意帮你解答
